### ISSUE TITLE
New Bible Versions

### ISSUE THREAD

**Issue by dgrah50** [edwinyosorahardjo/lzbible#1]
Hey! I would love to help you to compress some more versions. Can you expand on the process to do so?

**Comment by edwinyosorahardjo** [comment]
Hi @dgrah50,
Sorry for the late reply.
Thank you, I would love some help.
I don't have proper process for contribution at the moment.
You can create pull request for new bible files.
I am using C# to extract csv bible database, I will commit this code for you to use.

**Comment by edwinyosorahardjo** [comment]
I have added all bibles from bibledatabase.org and the C# code to update the repo
You can alter it to convert and add more bibles.
